export const INITIALIZED_SUCCESS = 'app/INITIALIZED_SUCCESS';

export const GET_ARTICLES = 'article/GET_ARTICLES';
export const GET_CURRENT_ARTICLE = 'article/GET_CURRENT_ARTICLE';
export const INSTALL_DOWNLOAD_ARTICLE = 'article/INSTALL DOWNLOAD ARTICLE';
export const INSTALL_DOWNLOAD_ARTICLES = 'article/INSTALL_DOWNLOAD_ARTICLES';
export const SET_CURRENT_PAGE = 'articles/SET_CURRENT_PAGE';
export const SET_ARTICLES_COUNT = 'articles/SET_ARTICLES_COUNT';
export const SET_OPEN_ARTICLE = 'articles/SET_OPEN_ARTICLE';
export const SET_SUCCESSFUL_ARTICLE_CREATION = 'articles/SET_SUCCESSFUL_ARTICLE_CREATION';
export const SET_LIKE_ARTICLE = 'article/SET_LIKE_ARTICLE';

export const SET_UPDATE_AUTH_USER = 'auth/SET_UPDATE_AUTH_USER';
export const GET_LOGGED_IN = 'auth/GET_LOGGED_IN';
export const INSTALL_EDITED_PROFILE = 'auth/INSTALL_EDITED_PROFILE';